name: Convert Notion to Blog

# on:
#   schedule:
#     - cron: '0 0 * * *'
on: [push]

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pnpm install

      - name: Convert Notion to Blog
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          NOTION_BLOG_PAGE: ${{ secrets.NOTION_BLOG_PAGE }}
        run: pnpm run notion-to-blog

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "feat: sync notion to blog"
          git push
